<?php

namespace app\controllers;

use Yii;
use app\models\Place;
use app\models\PlaceSearch;
use yii\db\Exception;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;

/**
 * PlaceController implements the CRUD actions for Place model.
 */
class PlaceController extends Controller
{
    public $layout = "index";

    public function beforeAction($action)
    {
        if(Yii::$app->language != Yii::$app->session->get("lang"))
            Yii::$app->language = Yii::$app->session->get("lang");

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Place models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new PlaceSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Place model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Place model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Place();

        if ($model->load(Yii::$app->request->post())) {
            $tx = Yii::$app->db->beginTransaction();
            try{
                $model->user_id = Yii::$app->user->id;
                $model->last_update = date("Y-m-d H:i:s");
                if(!$model->save())
                    throw new  Exception(json_encode($model->errors));

                $model->logouploader = UploadedFile::getInstance($model, "logouploader");
                $filename = date("YmdHis").rand(100, 999). ".". $model->logouploader->extension;
                if(!file_exists(Yii::$app->params["UPLOADPATH"]))
                    mkdir(Yii::$app->params["UPLOADPATH"]);

                if(!file_exists(Yii::$app->params["LOGOPATH"]))
                    mkdir(Yii::$app->params["LOGOPATH"]);

                if(!file_exists(Yii::$app->params["PHOTOPATH"]))
                    mkdir(Yii::$app->params["PHOTOPATH"]);

                if(!file_exists(Yii::$app->params["LOGOPATH"].$filename))
                    if(!$model->logouploader->saveAs(Yii::$app->params["LOGOPATH"].$filename))
                        throw new Exception(Yii::t("app", "Cannot Upload Logo"));

                $tx->commit();
                return $this->redirect(['view', 'id' => $model->id]);
            } catch (Exception $ex) {
                $tx->rollBack();
                Yii::$app->session->setFlash("danger", $ex->getMessage());
            }
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Place model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Place model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Place model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Place the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Place::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    public function actionUpdatephoto($id) {
        $model = $this->findModel($id);
        return $this->render('photo', [
            'model' => $model
        ]);
    }

    public function actionSyncfirebase() {

    }
}
